// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProFinder.Infrastructure.Data;

#nullable disable

namespace ProFinder.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ProFinderDbContext))]
    [Migration("20260307130437_AddGoogleMapsLeads")]
    partial class AddGoogleMapsLeads
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProFinder.Domain.Entities.Evidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProfessionalId")
                        .HasColumnType("int");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalId");

                    b.ToTable("prf_evidences", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CollectedAt = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            FieldName = "Telefone",
                            FieldValue = "11 98765-4321",
                            ProfessionalId = 1,
                            SourceUrl = "https://maps.example.com/cheletrica"
                        },
                        new
                        {
                            Id = 2,
                            CollectedAt = new DateTime(2026, 1, 15, 13, 0, 0, 0, DateTimeKind.Utc),
                            FieldName = "Instagram",
                            FieldValue = "@mshidraulica",
                            ProfessionalId = 2,
                            SourceUrl = "https://instagram.com/mshidraulica"
                        });
                });

            modelBuilder.Entity("ProFinder.Domain.Entities.GoogleMapsLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImportStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ImportedProfessionalId")
                        .HasColumnType("int");

                    b.Property<int>("LeadCaptureRunId")
                        .HasColumnType("int");

                    b.Property<int>("LeadSourceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PlaceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ProfessionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SearchQuery")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("ImportedProfessionalId");

                    b.HasIndex("LeadCaptureRunId");

                    b.HasIndex("LeadSourceId");

                    b.HasIndex("PlaceUrl")
                        .IsUnique();

                    b.HasIndex("ProfessionId");

                    b.HasIndex("RegionId");

                    b.HasIndex("NormalizedPhone", "Name");

                    b.ToTable("prf_google_maps_leads", (string)null);
                });

            modelBuilder.Entity("ProFinder.Domain.Entities.Interaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("InteractionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProfessionalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalId", "InteractionDate");

                    b.ToTable("prf_interactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Admin",
                            Description = "Primeiro contato realizado, respondeu rapidamente.",
                            InteractionDate = new DateTime(2026, 2, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            InteractionType = "WhatsApp",
                            ProfessionalId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Admin",
                            Description = "Agendou retorno para a próxima semana.",
                            InteractionDate = new DateTime(2026, 2, 3, 9, 30, 0, 0, DateTimeKind.Utc),
                            InteractionType = "PhoneCall",
                            ProfessionalId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Admin",
                            Description = "Enviou portfólio e tabela de preços.",
                            InteractionDate = new DateTime(2026, 2, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            InteractionType = "Email",
                            ProfessionalId = 2
                        });
                });

            modelBuilder.Entity("ProFinder.Domain.Entities.LeadCaptureRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaptureType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FileName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ItemsCaptured")
                        .HasColumnType("int");

                    b.Property<int>("ItemsInserted")
                        .HasColumnType("int");

                    b.Property<int>("ItemsSkipped")
                        .HasColumnType("int");

                    b.Property<int>("ItemsUpdated")
                        .HasColumnType("int");

                    b.Property<int?>("LeadSourceId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SearchQuery")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LeadSourceId");

                    b.ToTable("prf_lead_capture_runs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaptureType = "CsvImport",
                            CompletedAt = new DateTime(2026, 1, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 1, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "Seeder",
                            FileName = "eletricistas-sp.csv",
                            ItemsCaptured = 0,
                            ItemsInserted = 0,
                            ItemsSkipped = 0,
                            ItemsUpdated = 0,
                            LeadSourceId = 2,
                            Notes = "Importação futura via CSV.",
                            StartedAt = new DateTime(2026, 1, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = "PendingImplementation",
                            UpdatedAt = new DateTime(2026, 1, 2, 8, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ProFinder.Domain.Entities.LeadSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("prf_lead_sources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lead inserido manualmente no painel.",
                            IsActive = true,
                            Name = "Cadastro manual"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lead importado por arquivo CSV.",
                            IsActive = true,
                            Name = "Importação CSV"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lead identificado a partir de busca pública.",
                            IsActive = true,
                            Name = "Google Maps",
                            Url = "https://www.google.com/maps"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lead captado via site do profissional.",
                            IsActive = true,
                            Name = "Site próprio"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Lead recebido por indicação.",
                            IsActive = true,
                            Name = "Indicação"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Outras fontes públicas ou privadas.",
                            IsActive = true,
                            Name = "Outro"
                        });
                });

            modelBuilder.Entity("ProFinder.Domain.Entities.LeadStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("prf_lead_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lead recém-cadastrado.",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Novo"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lead em validação.",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Em análise"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lead com critérios mínimos atendidos.",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Qualificado"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Primeiro contato realizado.",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Contatado"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Lead demonstrou interesse.",
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "Interessado"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Lead sem interesse no momento.",
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "Não interessado"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Lead com dados inconsistentes.",
                            DisplayOrder = 7,
                            IsActive = true,
                            Name = "Inválido"
                        });
                });

            modelBuilder.Entity("ProFinder.Domain.Entities.Profession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("prf_professions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Profissionais de instalações e manutenção elétrica.",
                            IsActive = true,
                            Name = "Eletricista"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Profissionais de hidráulica e reparos em geral.",
                            IsActive = true,
                            Name = "Encanador"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Profissionais de pintura residencial e comercial.",
                            IsActive = true,
                            Name = "Pintor"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Profissionais especializados em abertura e cópia de chaves.",
                            IsActive = true,
                            Name = "Chaveiro"
                        });
                });

            modelBuilder.Entity("ProFinder.Domain.Entities.Professional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Instagram")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAutonomous")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProfessionId")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("FullName");

                    b.HasIndex("IsActive");

                    b.HasIndex("Phone");

                    b.HasIndex("ProfessionId");

                    b.HasIndex("SourceId");

                    b.HasIndex("StatusId");

                    b.HasIndex("WhatsApp");

                    b.ToTable("prf_professionals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessName = "CH Elétrica",
                            CreatedAt = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carlos@cheletrica.com.br",
                            FullName = "Carlos Henrique Silva",
                            Instagram = "@cheletrica",
                            IsActive = true,
                            IsAutonomous = true,
                            Notes = "Atende residências e pequenos comércios.",
                            Phone = "11987654321",
                            ProfessionId = 1,
                            SourceId = 1,
                            StatusId = 4,
                            UpdatedAt = new DateTime(2026, 2, 3, 15, 30, 0, 0, DateTimeKind.Utc),
                            Website = "https://cheletrica.example.com",
                            WhatsApp = "11987654321"
                        },
                        new
                        {
                            Id = 2,
                            BusinessName = "MS Hidráulica",
                            CreatedAt = new DateTime(2026, 1, 12, 14, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mariana@hidraulicaexemplo.com.br",
                            FullName = "Mariana Souza",
                            Instagram = "@mshidraulica",
                            IsActive = true,
                            IsAutonomous = true,
                            Notes = "Especialista em reparos rápidos.",
                            Phone = "11981234567",
                            ProfessionId = 2,
                            SourceId = 3,
                            StatusId = 3,
                            UpdatedAt = new DateTime(2026, 2, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            WhatsApp = "11981234567"
                        },
                        new
                        {
                            Id = 3,
                            BusinessName = "Pinturas Lima",
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "roberto@pinturaslima.com.br",
                            FullName = "Roberto Lima",
                            IsActive = true,
                            IsAutonomous = true,
                            Notes = "Orçamentos por foto e visita técnica.",
                            Phone = "19999887766",
                            ProfessionId = 3,
                            SourceId = 2,
                            StatusId = 1,
                            UpdatedAt = new DateTime(2026, 1, 20, 10, 30, 0, 0, DateTimeKind.Utc),
                            Website = "https://pinturaslima.example.com"
                        });
                });

            modelBuilder.Entity("ProFinder.Domain.Entities.ProfessionalRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfidenceLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsPrimaryRegion")
                        .HasColumnType("bit");

                    b.Property<int>("ProfessionalId")
                        .HasColumnType("int");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("ProfessionalId", "RegionId")
                        .IsUnique();

                    b.ToTable("prf_professional_regions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConfidenceLevel = "Alta",
                            IsPrimaryRegion = true,
                            ProfessionalId = 1,
                            RegionId = 1
                        },
                        new
                        {
                            Id = 2,
                            ConfidenceLevel = "Média",
                            IsPrimaryRegion = false,
                            ProfessionalId = 1,
                            RegionId = 2
                        },
                        new
                        {
                            Id = 3,
                            ConfidenceLevel = "Alta",
                            IsPrimaryRegion = true,
                            ProfessionalId = 2,
                            RegionId = 2
                        },
                        new
                        {
                            Id = 4,
                            ConfidenceLevel = "Média",
                            IsPrimaryRegion = false,
                            ProfessionalId = 2,
                            RegionId = 4
                        },
                        new
                        {
                            Id = 5,
                            ConfidenceLevel = "Alta",
                            IsPrimaryRegion = true,
                            ProfessionalId = 3,
                            RegionId = 3
                        });
                });

            modelBuilder.Entity("ProFinder.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("RadiusKm")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Zone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("State", "City", "Neighborhood", "ZipCode");

                    b.ToTable("prf_regions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "São Paulo",
                            IsActive = true,
                            Latitude = -23.540100m,
                            Longitude = -46.576400m,
                            Neighborhood = "Tatuapé",
                            RadiusKm = 5m,
                            State = "SP",
                            ZipCode = "03301000",
                            Zone = "Leste"
                        },
                        new
                        {
                            Id = 2,
                            City = "São Paulo",
                            IsActive = true,
                            Latitude = -23.556200m,
                            Longitude = -46.601700m,
                            Neighborhood = "Mooca",
                            RadiusKm = 5m,
                            State = "SP",
                            ZipCode = "03104000",
                            Zone = "Leste"
                        },
                        new
                        {
                            Id = 3,
                            City = "Campinas",
                            IsActive = true,
                            Latitude = -22.891400m,
                            Longitude = -47.060800m,
                            Neighborhood = "Cambuí",
                            RadiusKm = 8m,
                            State = "SP",
                            ZipCode = "13024000",
                            Zone = "Central"
                        },
                        new
                        {
                            Id = 4,
                            City = "Santo André",
                            IsActive = true,
                            Latitude = -23.663900m,
                            Longitude = -46.538300m,
                            Neighborhood = "Centro",
                            RadiusKm = 6m,
                            State = "SP",
                            ZipCode = "09015000",
                            Zone = "ABC"
                        });
                });

            modelBuilder.Entity("ProFinder.Domain.Entities.Evidence", b =>
                {
                    b.HasOne("ProFinder.Domain.Entities.Professional", "Professional")
                        .WithMany("Evidences")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("ProFinder.Domain.Entities.GoogleMapsLead", b =>
                {
                    b.HasOne("ProFinder.Domain.Entities.Professional", "ImportedProfessional")
                        .WithMany()
                        .HasForeignKey("ImportedProfessionalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProFinder.Domain.Entities.LeadCaptureRun", "LeadCaptureRun")
                        .WithMany("GoogleMapsLeads")
                        .HasForeignKey("LeadCaptureRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProFinder.Domain.Entities.LeadSource", "LeadSource")
                        .WithMany("GoogleMapsLeads")
                        .HasForeignKey("LeadSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProFinder.Domain.Entities.Profession", "Profession")
                        .WithMany()
                        .HasForeignKey("ProfessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProFinder.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ImportedProfessional");

                    b.Navigation("LeadCaptureRun");

                    b.Navigation("LeadSource");

                    b.Navigation("Profession");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("ProFinder.Domain.Entities.Interaction", b =>
                {
                    b.HasOne("ProFinder.Domain.Entities.Professional", "Professional")
                        .WithMany("Interactions")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("ProFinder.Domain.Entities.LeadCaptureRun", b =>
                {
                    b.HasOne("ProFinder.Domain.Entities.LeadSource", "LeadSource")
                        .WithMany("LeadCaptureRuns")
                        .HasForeignKey("LeadSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LeadSource");
                });

            modelBuilder.Entity("ProFinder.Domain.Entities.Professional", b =>
                {
                    b.HasOne("ProFinder.Domain.Entities.Profession", "Profession")
                        .WithMany("Professionals")
                        .HasForeignKey("ProfessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProFinder.Domain.Entities.LeadSource", "Source")
                        .WithMany("Professionals")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProFinder.Domain.Entities.LeadStatus", "Status")
                        .WithMany("Professionals")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profession");

                    b.Navigation("Source");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ProFinder.Domain.Entities.ProfessionalRegion", b =>
                {
                    b.HasOne("ProFinder.Domain.Entities.Professional", "Professional")
                        .WithMany("ProfessionalRegions")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProFinder.Domain.Entities.Region", "Region")
                        .WithMany("ProfessionalRegions")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professional");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("ProFinder.Domain.Entities.LeadCaptureRun", b =>
                {
                    b.Navigation("GoogleMapsLeads");
                });

            modelBuilder.Entity("ProFinder.Domain.Entities.LeadSource", b =>
                {
                    b.Navigation("GoogleMapsLeads");

                    b.Navigation("LeadCaptureRuns");

                    b.Navigation("Professionals");
                });

            modelBuilder.Entity("ProFinder.Domain.Entities.LeadStatus", b =>
                {
                    b.Navigation("Professionals");
                });

            modelBuilder.Entity("ProFinder.Domain.Entities.Profession", b =>
                {
                    b.Navigation("Professionals");
                });

            modelBuilder.Entity("ProFinder.Domain.Entities.Professional", b =>
                {
                    b.Navigation("Evidences");

                    b.Navigation("Interactions");

                    b.Navigation("ProfessionalRegions");
                });

            modelBuilder.Entity("ProFinder.Domain.Entities.Region", b =>
                {
                    b.Navigation("ProfessionalRegions");
                });
#pragma warning restore 612, 618
        }
    }
}
